// <auto-generated />
using System;
using LiliMagic.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LiliMagic.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("LiliMagic.Api.Core.Drawing", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CanvasHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CanvasWidth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Drawings");
                });

            modelBuilder.Entity("LiliMagic.Api.Core.Layer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("BlendMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("DrawingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Opacity")
                        .HasColumnType("REAL");

                    b.Property<int>("ZIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DrawingId");

                    b.ToTable("Layers");

                    b.HasDiscriminator().HasValue("Layer");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LiliMagic.Api.Core.MimiMemory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MimiMemories");
                });

            modelBuilder.Entity("LiliMagic.Api.Core.RasterLayer", b =>
                {
                    b.HasBaseType("LiliMagic.Api.Core.Layer");

                    b.Property<string>("DataUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("raster");
                });

            modelBuilder.Entity("LiliMagic.Api.Core.SkeletalLayer", b =>
                {
                    b.HasBaseType("LiliMagic.Api.Core.Layer");

                    b.Property<string>("BonesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IkChainsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SmartActionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("skeletal");
                });

            modelBuilder.Entity("LiliMagic.Api.Core.VectorLayer", b =>
                {
                    b.HasBaseType("LiliMagic.Api.Core.Layer");

                    b.Property<string>("FillColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PathsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StrokeColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("StrokeWidth")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("vector");
                });

            modelBuilder.Entity("LiliMagic.Api.Core.Layer", b =>
                {
                    b.HasOne("LiliMagic.Api.Core.Drawing", null)
                        .WithMany("Layers")
                        .HasForeignKey("DrawingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LiliMagic.Api.Core.Drawing", b =>
                {
                    b.Navigation("Layers");
                });
#pragma warning restore 612, 618
        }
    }
}
