import React, { useEffect, useRef, useCallback, useState } from 'react';

// ─── SVG Assets ───────────────────────────────────────────────────────────────
// CRITICAL: viewBox must match the actual coordinate space of the <path> data.
// These SVGs were generated by potrace at 10× resolution, so viewBox values
// are 10× the original pixel dimensions (e.g., 1280px → 12800 units).

// SVG for Cat Paw (Retracted Claws) - PATA SEM GARRAS.svg
// Path coords span ~2095–10570 in X, ~1200–12476 in Y → viewBox 0 0 12800 12800
const PawRetractedSVG = `
<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 12800 12800" preserveAspectRatio="xMidYMid meet">
<g fill="currentColor" stroke="none">
<path d="M4615 12476 c-167 -39 -293 -112 -436 -255 -116 -115 -199 -232 -279
-391 -477 -954 -316 -2528 353 -3430 91 -123 249 -285 357 -366 354 -267 752
-281 1071 -38 327 250 551 732 636 1369 21 164 25 672 5 840 -82 702 -291
1283 -618 1722 -82 109 -243 273 -344 350 -94 71 -272 163 -365 188 -83 23
-302 29 -380 11z"/>
<path d="M8546 12274 c-311 -61 -636 -299 -905 -661 -346 -465 -580 -1080
-668 -1758 -28 -216 -25 -698 5 -894 70 -447 219 -789 442 -1011 191 -192 431
-281 675 -252 581 72 1154 706 1460 1616 254 755 281 1550 73 2156 -203 591
-615 897 -1082 804z"/>
<path d="M2095 9010 c-409 -65 -717 -395 -856 -919 -79 -301 -90 -716 -28
-1081 143 -850 635 -1631 1217 -1933 298 -154 595 -181 850 -75 376 156 623
560 704 1153 16 119 16 472 -1 610 -130 1102 -809 2069 -1564 2230 -89 19
-247 26 -322 15z"/>
<path d="M10570 8200 c-360 -77 -713 -330 -1006 -722 -318 -426 -532 -982
-594 -1542 -16 -146 -13 -460 5 -601 122 -948 766 -1403 1495 -1059 391 185
745 566 998 1073 480 960 449 2085 -73 2606 -220 220 -523 310 -825 245z"/>
<path d="M6225 6421 c-662 -118 -1497 -813 -2237 -1861 -579 -821 -987 -1705
-1109 -2405 -29 -168 -32 -468 -6 -583 41 -179 110 -297 244 -422 224 -207
493 -329 830 -376 175 -24 529 -15 754 19 301 47 555 108 1124 272 550 158
704 191 856 181 193 -13 338 -60 754 -243 298 -131 464 -193 606 -228 530
-128 976 39 1435 537 137 148 179 220 222 377 24 90 26 110 26 321 0 191 -3
245 -23 355 -118 667 -469 1473 -976 2240 -603 912 -1311 1569 -1902 1764
-215 71 -398 87 -598 52z"/>
</g>
</svg>
`;

// SVG for Cat Paw (Claws Out) - PARA COM GARRAS.svg
// Path coords span ~435–9446 in X, ~635–12755 in Y → viewBox 0 0 9960 12800
const PawClawsOutSVG = `
<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 9960 12800" preserveAspectRatio="xMidYMid meet">
<g fill="currentColor" stroke="none">
<path d="M3608 12755 c-3 -17 -57 -403 -119 -858 l-114 -828 -109 -132 c-60
-73 -123 -146 -140 -163 -247 -242 -456 -697 -555 -1204 -98 -505 -96 -1082 4
-1585 117 -582 362 -1055 668 -1286 272 -206 575 -214 844 -22 367 261 637
831 737 1558 22 155 30 275 20 275 -5 0 -9 123 -9 273 0 266 -11 424 -41 615
-77 483 -252 978 -438 1231 -96 133 -260 278 -384 340 -40 20 -49 32 -89 118
l-46 96 -58 421 c-32 232 -81 588 -109 791 -28 204 -52 374 -54 380 -1 5 -5
-4 -8 -20z"/>
<path d="M6476 12625 c-4 -22 -65 -335 -136 -695 -71 -360 -148 -753 -172
-872 l-42 -217 -92 -61 c-220 -145 -404 -403 -498 -695 -175 -548 -252 -973
-263 -1457 -3 -137 -10 -248 -14 -248 -13 0 -11 -47 6 -195 95 -824 420 -1476
844 -1699 195 -102 427 -102 621 0 359 188 655 694 790 1351 99 476 106 1056
19 1543 -90 507 -293 971 -539 1234 -42 44 -121 135 -175 201 l-100 120 -117
850 c-65 467 -119 856 -121 865 -2 8 -6 -3 -11 -25z"/>
<path d="M435 9456 c-193 -87 -351 -454 -411 -956 -24 -200 -24 -602 0 -795
32 -253 83 -467 147 -620 27 -61 29 -76 23 -135 -8 -84 11 -341 37 -495 158
-948 809 -1890 1458 -2111 147 -50 250 -62 368 -42 139 24 226 69 329 172 163
164 253 401 273 725 26 429 -72 894 -289 1371 -386 851 -1079 1428 -1590 1327
-41 -9 -78 -12 -82 -9 -10 11 -75 202 -103 305 -109 403 -140 864 -81 1205
l12 72 -30 0 c-17 -1 -44 -7 -61 -14z"/>
<path d="M9446 9393 c70 -396 13 -953 -140 -1388 -35 -100 -45 -120 -61 -119
-11 1 -63 7 -115 13 -153 19 -297 -12 -485 -105 -332 -164 -675 -525 -925
-969 -298 -531 -451 -1128 -419 -1630 19 -291 99 -526 233 -685 493 -585 1515
62 2002 1267 148 368 223 718 228 1078 3 167 5 184 28 240 105 245 161 598
161 1005 0 462 -74 853 -210 1112 -80 151 -197 258 -284 258 l-26 0 13 -77z"/>
<path d="M4805 5683 c-168 -14 -371 -71 -519 -145 -151 -75 -217 -123 -288
-207 -207 -244 -335 -472 -557 -988 -66 -155 -137 -306 -158 -335 -188 -266
-478 -492 -718 -558 -434 -118 -855 -347 -1088 -589 -112 -117 -169 -198 -261
-372 -131 -250 -188 -485 -187 -783 0 -283 59 -531 181 -771 148 -289 408
-553 679 -690 100 -50 366 -157 441 -177 90 -24 274 -28 365 -9 77 17 307 90
408 130 109 44 154 68 297 158 435 276 743 407 1105 470 154 26 482 24 640 -6
428 -79 751 -217 1269 -544 245 -155 363 -208 551 -249 100 -22 370 -16 494
11 305 65 553 188 762 378 452 410 635 1022 494 1649 -72 317 -289 669 -538
873 -155 126 -194 145 -454 220 -317 92 -428 137 -586 238 -171 109 -336 271
-450 443 -90 135 -101 160 -312 695 -150 382 -185 461 -228 520 -317 440 -826
682 -1342 638z"/>
</g>
</svg>
`;

// SVG for Canvas Drawing Tool - garra-cursor.svg
const GarraCanvasSVG = `
<svg version="1.0" xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 700 1280" preserveAspectRatio="xMidYMid meet">
<g transform="translate(0.000000,1280.000000) scale(0.100000,-0.100000)"
fill="currentColor" stroke="none">
<path d="M2750 12642 c-43 -5 -120 -33 -120 -43 0 -5 35 -67 77 -137 353 -585
633 -1395 777 -2247 70 -415 118 -1050 85 -1143 -9 -27 -18 -32 -92 -52 -164
-43 -293 -82 -362 -107 -533 -196 -1080 -808 -1445 -1616 -378 -835 -575
-1758 -597 -2802 -26 -1237 242 -2420 734 -3245 359 -601 779 -946 1298 -1066
63 -15 120 -19 270 -19 175 0 198 2 295 27 378 99 702 314 1026 680 511 579
897 1446 1098 2466 159 807 186 1706 76 2530 -64 482 -175 920 -355 1412 -126
344 -126 345 -131 604 -4 243 -22 441 -59 673 -161 993 -679 2283 -1234 3077
-270 385 -553 678 -816 843 -173 109 -402 181 -525 165z"/>
</g>
</svg>
`;

// SVG for Cat Paw (Generic) - for main cursor
const PawCursorSVG_Content = `
<svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
  <!-- Main pad -->
  <ellipse cx="20" cy="25" rx="10" ry="12" fill="currentColor"/>
  <!-- Toes -->
  <circle cx="12" cy="12" r="5" fill="currentColor"/>
  <circle cx="20" cy="10" r="5" fill="currentColor"/>
  <circle cx="28" cy="12" r="5" fill="currentColor"/>
</svg>
`;

const PegadasSVG_Content = `
<svg version="1.0" xmlns="http://www.w3.org/2000/svg"
 width="96" height="96" viewBox="0 0 700.000000 1280.000000"
 preserveAspectRatio="xMidYMid meet">
<g transform="translate(0.000000,1280.000000) scale(0.100000,-0.100000)"
fill="currentColor" stroke="none">
<path d="M2705 12291 c-163 -42 -283 -208 -322 -444 -23 -136 -10 -238 41
-343 48 -97 81 -133 153 -170 96 -48 183 -33 295 53 178 136 252 489 149 709
-66 141 -201 225 -316 195z"/>
<path d="M1678 12223 c-60 -35 -119 -113 -144 -189 -15 -46 -19 -86 -18 -184
0 -108 4 -136 27 -207 67 -201 239 -363 386 -365 162 -1 281 164 281 392 0
118 -22 209 -75 316 -80 164 -200 256 -340 262 -62 3 -76 0 -117 -25z"/>
<path d="M3356 11529 c-214 -33 -385 -279 -388 -554 -1 -134 63 -260 157 -312
181 -99 443 95 509 377 19 81 20 212 3 271 -18 60 -78 151 -117 179 -47 33
-107 48 -164 39z"/>
<path d="M1178 11397 c-68 -22 -127 -73 -155 -133 -66 -145 -28 -358 98 -540
55 -80 182 -160 291 -184 49 -11 63 -11 100 3 61 24 109 67 143 128 26 47 30
66 33 154 5 119 -12 197 -65 297 -39 75 -125 175 -187 217 -85 57 -189 81
-258 58z"/>
<path d="M2265 10914 c-210 -41 -363 -149 -496 -348 -139 -207 -254 -530 -235
-662 19 -140 127 -233 272 -234 80 0 125 12 314 82 195 73 231 82 350 82 102
0 111 -2 293 -62 224 -75 253 -79 338 -58 79 20 137 61 167 117 34 64 28 182
-16 295 -83 211 -317 521 -493 654 -180 135 -310 171 -494 134z"/>
<path d="M5175 9005 c-225 -91 -354 -493 -239 -745 80 -175 217 -253 354 -201
165 62 286 267 297 501 16 331 -178 540 -412 445z"/>
<path d="M4223 8971 c-51 -24 -116 -87 -143 -140 -47 -93 -62 -249 -35 -376
18 -86 93 -238 148 -302 92 -103 221 -158 313 -133 139 39 224 189 224 396 0
232 -126 463 -296 543 -68 33 -157 38 -211 12z"/>
<path d="M5818 8246 c-90 -37 -151 -81 -198 -143 -202 -270 -163 -648 74 -723
125 -40 312 72 399 237 54 103 77 199 77 318 0 112 -13 150 -76 236 -72 98
-162 122 -276 75z"/>
<path d="M3672 8124 c-98 -36 -154 -137 -155 -284 -3 -193 81 -367 229 -478
71 -53 168 -92 230 -92 48 0 94 21 144 66 55 50 78 98 92 192 23 164 -46 349
-181 482 -42 41 -98 86 -126 100 -63 31 -169 37 -233 14z"/>
<path d="M4795 7655 c-131 -24 -278 -99 -379 -194 -172 -165 -357 -566 -359
-781 -1 -104 58 -206 144 -251 95 -48 190 -35 452 64 181 69 239 81 364 75 87
-4 119 -12 284 -66 202 -68 253 -74 347 -47 58 18 115 62 139 109 75 143 2
346 -238 672 -168 228 -343 366 -516 408 -87 21 -160 25 -238 11z"/>
<path d="M2349 6285 c-95 -35 -163 -101 -224 -215 -132 -252 -90 -589 88 -708
97 -65 154 -69 256 -18 90 46 151 109 200 206 56 112 74 204 69 349 -4 110 -6
122 -40 192 -46 95 -99 156 -162 185 -58 27 -130 30 -187 9z"/>
<path d="M1397 6248 c-55 -15 -131 -89 -166 -161 -55 -113 -62 -240 -24 -397
51 -212 221 -392 384 -408 98 -9 215 78 258 193 82 219 15 514 -153 673 -90
86 -208 125 -299 100z"/>
<path d="M3010 5531 c-60 -12 -159 -72 -209 -126 -102 -113 -155 -254 -156
-420 0 -103 2 -114 31 -176 77 -162 209 -209 368 -130 270 133 374 598 177
789 -41 40 -114 73 -155 71 -12 -1 -37 -4 -56 -8z"/>
<path d="M815 5387 c-104 -50 -150 -140 -148 -292 2 -200 115 -405 275 -499
98 -57 202 -71 275 -35 214 103 197 483 -32 716 -88 89 -159 126 -255 131 -52
2 -75 -2 -115 -21z"/>
<path d="M1892 4910 c-85 -23 -208 -85 -285 -145 -143 -113 -302 -394 -373
-662 -55 -204 -21 -320 116 -401 39 -24 56 -27 130 -27 90 0 82 -2 425 122 95
35 106 37 230 37 l130 1 170 -57 c94 -31 186 -60 205 -64 147 -31 291 50 321
180 30 134 -60 345 -255 601 -230 302 -430 435 -651 434 -55 0 -118 -7 -163
-19z"/>
<path d="M5310 3078 c-169 -82 -272 -278 -274 -518 0 -154 34 -257 117 -348
81 -87 200 -116 294 -71 154 75 267 269 280 485 10 166 -27 292 -114 385 -94
101 -189 122 -303 67z"/>
<path d="M4384 3052 c-63 -22 -99 -50 -141 -109 -53 -75 -68 -133 -68 -263 0
-63 6 -140 14 -170 68 -277 311 -477 487 -401 125 54 194 188 194 377 0 233
-121 464 -285 545 -80 39 -134 45 -201 21z"/>
<path d="M5996 2339 c-162 -39 -307 -206 -351 -404 -25 -110 -18 -243 16 -315
75 -161 210 -211 364 -136 75 37 170 132 213 213 71 134 93 327 51 450 -46
139 -172 221 -293 192z"/>
<path d="M3820 2204 c-93 -32 -145 -108 -162 -237 -9 -68 -8 -96 5 -162 36
-177 154 -343 291 -411 83 -41 171 -54 229 -35 46 16 114 82 138 135 83 189
-3 481 -186 629 -115 92 -210 117 -315 81z"/>
<path d="M4890 1725 c-30 -8 -101 -38 -158 -66 -79 -40 -118 -67 -171 -119
-126 -125 -244 -329 -310 -535 -71 -220 -74 -277 -26 -380 29 -61 69 -99 134
-128 68 -30 169 -20 318 33 298 105 325 113 418 118 105 5 144 -3 375 -80 214
-70 270 -70 392 4 180 110 79 448 -248 832 -137 161 -267 260 -399 307 -79 28
-247 35 -325 14z"/>
</g>
</svg>
`;

const CURSOR_SIZE = 64; // Increased from 48
const PARTICLE_SIZE = 96; // Increased from 48 and now matches new SVG width/height
const MAX_PARTICLES = 50;
const PARTICLE_LIFETIME_MS = 1000;
const SPAWN_DISTANCE_THRESHOLD = 40; // px between footprints, increased from 30

const NEON_CURSOR_BASE_COLOR = '#FFEDF2'; // A subtle pinkish-white for the neon base

// Interactive tag names (uppercase for comparison)
const INTERACTIVE_TAGS = new Set([
  'BUTTON', 'A', 'INPUT', 'SELECT', 'TEXTAREA', 'LABEL', 'SUMMARY',
]);

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Check if an element (or any ancestor up to body) is "clickable" */
function isClickableElement(target: EventTarget | null): boolean {
  let el = target as HTMLElement | null;
  // Use closest for more efficient ancestor checking for most common interactive elements
  const clickableAncestor = el?.closest(
    'button, a, input, select, textarea, label, summary, [onclick], [data-clickable], [role="button"], [role="link"], [tabindex]:not([tabindex="-1"])'
  );
  if (clickableAncestor) return true;

  // Fallback for elements with cursor: pointer style, might still cause reflow if many checks happen
  return false;
}

/** Read CSS variable colors from :root */
function getThemeColors(): { primary: string; accent: string } {
  const s = getComputedStyle(document.documentElement);
  return {
    primary: s.getPropertyValue('--primary').trim() || '#818CF8',
    accent: s.getPropertyValue('--accent').trim() || '#F472B6',
  };
}

// ─── Global keyframe styles (injected once) ───────────────────────────────────
const GLOBAL_STYLE_CONTENT = `
  *, *::before, *::after { cursor: none !important; }
  #drawing-canvas { cursor: none !important; } /* Explicitly hide cursor on canvas */

  @keyframes paw-particle-fade {
    0%   { opacity: 1;   transform: scale(1); }
    50%  { opacity: 0.7; transform: scale(0.6); }
    100% { opacity: 0;   transform: scale(0.1); }
  }
`;

// ─── Component ────────────────────────────────────────────────────────────────

const CustomCursor: React.FC = () => {
  const cursorRef = useRef<HTMLDivElement>(null);
  const particleContainerRef = useRef<HTMLDivElement>(null);

  // Mutable state in refs — no re-renders
  const mousePos = useRef({ x: -200, y: -200 });
  const previousMousePos = useRef({ x: -200, y: -200 });
  const lastSpawnPos = useRef({ x: -200, y: -200 });
  const isPointer = useRef(false);
  const rafId = useRef(0);
  const particleCount = useRef(0);
  const particlePool = useRef<HTMLDivElement[]>([]); // New: Particle recycling pool

  const [cursorOverride, setCursorOverride] = useState<string | null>(null);
  const [themeColors, setThemeColors] = useState(getThemeColors()); // Cache theme colors
  const currentCursorSVG = useRef(PawRetractedSVG);

  // ── Event Bus Listener for cursor overrides ────────────────────────────────
  useEffect(() => {
    const handleSetCursor = (event: Event) => {
      const customEvent = event as CustomEvent;
      setCursorOverride(customEvent.detail.cursorType || null);
    };

    document.addEventListener('set-cursor', handleSetCursor);
    return () => {
      document.removeEventListener('set-cursor', handleSetCursor);
    };
  }, []);

  // ── rAF render loop ─────────────────────────────────────────────────────────
  const renderLoop = useCallback(() => {
    const cursor = cursorRef.current;
    if (cursor) {
      const { x, y } = mousePos.current;

      const isGarra = currentCursorSVG.current === GarraCanvasSVG;
      const scale = isPointer.current && !isGarra ? 1.2 : 1;

      // The actual hotspot of the fake cursor is its center.
      // For the 'garra' cursor, we need to visually offset it so the tip is at the mouse position.
      let offsetX = 0;
      let offsetY = 0;

      if (isGarra) {
        offsetX = 10;  // Adjusted offset for garra X based on user's image analysis
        offsetY = 32; // Adjusted offset for garra Y based on user's image analysis
      }

      cursor.style.left = `${x - (CURSOR_SIZE / 2) + offsetX}px`;
      cursor.style.top = `${y - (CURSOR_SIZE / 2) + offsetY}px`;
      cursor.style.transform = `scale(${scale}) ${isGarra ? '' : 'rotate(180deg)'}`;
    }
    rafId.current = requestAnimationFrame(renderLoop);
  }, [cursorOverride]); // Re-run render loop setup if override changes to recalculate offsets

  // ── Particle spawning ──────────────────────────────────────────────────────
  const spawnParticle = useCallback((x: number, y: number, angle: number, colors: { primary: string; accent: string }) => {
    const container = particleContainerRef.current;
    if (!container) return;

    // Enforce ceiling
    if (particleCount.current >= MAX_PARTICLES) {
      const oldest = container.firstChild;
      if (oldest) {
        container.removeChild(oldest);
        particleCount.current--;
      }
    }

    const color = Math.random() < 0.5 ? colors.primary : colors.accent;
    const rotation = angle;

    requestAnimationFrame(() => {
      // Try to get a particle from the pool
      let el = particlePool.current.pop();

      if (!el) {
        // Fallback: If pool is empty, create a new one (should not happen if MAX_PARTICLES is sufficient)
        el = document.createElement('div');
        el.style.position = 'fixed';
        el.style.width = `${PARTICLE_SIZE}px`;
        el.style.height = `${PARTICLE_SIZE}px`;
        el.style.pointerEvents = 'none';
        el.style.zIndex = '99998';
        el.innerHTML = `
          <div style="width: 100%; height: 100%;">
            ${PegadasSVG_Content}
          </div>
        `;
        container.appendChild(el);
      }

      // Cleanup listener (re-attached every spawn to handle recycling)
      const onAnimationEnd = () => {
        if (!el) return;
        el.style.display = 'none'; // Hide when animation ends
        el.style.opacity = '0';   // Reset opacity
        particlePool.current.push(el); // Return to pool
        particleCount.current--;
      };

      el.addEventListener('animationend', onAnimationEnd, { once: true });

      el.style.display = 'block'; // Make visible
      el.style.color = color;
      el.style.opacity = '0.8';
      el.style.filter = `drop-shadow(0 0 3px ${color})`;
      el.style.transform = `rotate(${rotation}deg)`; // Apply rotation to the outer div

      // Update position
      el.style.left = `${x - PARTICLE_SIZE / 2}px`; // Particles should be centered around the passed X,Y
      el.style.top = `${y - PARTICLE_SIZE / 2}px`; // Particles should be centered around the passed X,Y

      // Restart animation (reset animation state)
      const innerDiv = el.children[0] as HTMLElement;
      if (!innerDiv) {
        console.error("Particle element has no first child!", el);
        return;
      }
      innerDiv.style.animation = 'none';
      innerDiv.offsetHeight; // Trigger reflow to reset animation
      innerDiv.style.animation = `paw-particle-fade ${PARTICLE_LIFETIME_MS}ms ease-out forwards`;

      particleCount.current++;
    });
  }, [themeColors]); // Recreate spawnParticle if themeColors change

  // ── Mouse move handler ──────────────────────────────────────────────────────
  const onMouseMove = useCallback((e: MouseEvent) => {
    // --- Batch Reads ---
    const clientX = e.clientX;
    const clientY = e.clientY;
    const isOverClickable = isClickableElement(e.target);

    // Determine if current cursor is garra
    const isGarraActive = cursorOverride === 'garra';

    // Calculate effective mouse position for cursor placement
    mousePos.current.x = clientX;
    mousePos.current.y = clientY;

    // Calculate effective spawn position for particles (hotspot)
    let spawnPointX = clientX;
    let spawnPointY = clientY;

    // Apply offset for garra for spawning particles from its tip
    if (isGarraActive) {
      spawnPointX += 10; // Garra offsetX
      spawnPointY += 32; // Garra offsetY
    }
    // For non-garra, particles spawn from the raw mouse position, which
    // corresponds to the center of the paw cursor due to `el.style.left = `${x - PARTICLE_SIZE / 2}px`;` in spawnParticle.

    // --- Determine desired SVG based on reads ---
    let desiredSVG;
    if (isGarraActive) {
      desiredSVG = GarraCanvasSVG;
      isPointer.current = false; // Disable scaling effect for garra
    } else {
      desiredSVG = isOverClickable ? PawClawsOutSVG : PawRetractedSVG;
      isPointer.current = isOverClickable;
    }

    // --- Batch Writes (cursor visual update) ---
    if (desiredSVG !== currentCursorSVG.current) {
      const cursor = cursorRef.current;
      if (cursor) {
        cursor.innerHTML = desiredSVG;
        currentCursorSVG.current = desiredSVG;
        cursor.style.color = NEON_CURSOR_BASE_COLOR; // Use the neon base color
        cursor.style.filter = `drop-shadow(0 0 8px ${themeColors.primary}) drop-shadow(0 0 18px ${themeColors.accent})`; // Use cached themeColors
      }
    }

    // --- Particle Spawning ---
    const dx = spawnPointX - lastSpawnPos.current.x;
    const dy = spawnPointY - lastSpawnPos.current.y;

    if (dx * dx + dy * dy > SPAWN_DISTANCE_THRESHOLD * SPAWN_DISTANCE_THRESHOLD) {
      lastSpawnPos.current.x = spawnPointX;
      lastSpawnPos.current.y = spawnPointY;

      const currentDx = spawnPointX - previousMousePos.current.x;
      const currentDy = spawnPointY - previousMousePos.current.y;
      let angle = 0;
      if (currentDx !== 0 || currentDy !== 0) {
        angle = Math.atan2(currentDy, currentDx) * 180 / Math.PI + 90;
      }

      const ox = (Math.random() - 0.5) * 14;
      const oy = (Math.random() - 0.5) * 14;

      // Pass calculated spawnPointX, spawnPointY and cached themeColors
      spawnParticle(spawnPointX + ox, spawnPointY + oy, angle, themeColors);
    }

    previousMousePos.current.x = spawnPointX; // Update previousMousePos with effective spawn point
    previousMousePos.current.y = spawnPointY; // Update previousMousePos with effective spawn point
  }, [spawnParticle, cursorOverride, themeColors]); // Add themeColors to dependency array

  // ── Mount / Unmount ─────────────────────────────────────────────────────────
  useEffect(() => {
    // 1. Inject global styles (cursor hide + particle keyframes)
    const styleEl = document.createElement('style');
    styleEl.setAttribute('data-custom-cursor', '');
    styleEl.textContent = GLOBAL_STYLE_CONTENT;
    document.head.appendChild(styleEl);

    // 2. Initialize cursor appearance
    const cursor = cursorRef.current;
    if (cursor) {
      cursor.innerHTML = PawRetractedSVG;
      currentCursorSVG.current = PawRetractedSVG; // Initialize the ref
      cursor.style.color = NEON_CURSOR_BASE_COLOR; // Use the neon base color
      cursor.style.filter =
        `drop-shadow(0 0 8px ${themeColors.primary}) drop-shadow(0 0 18px ${themeColors.accent})`; // Use cached themeColors
    }

    // 2.5 Pre-create and pool particles
    const container = particleContainerRef.current;
    if (container) {
      for (let i = 0; i < MAX_PARTICLES; i++) {
        const el = document.createElement('div');
        el.style.position = 'fixed';
        el.style.width = `${PARTICLE_SIZE}px`;
        el.style.height = `${PARTICLE_SIZE}px`;
        el.style.pointerEvents = 'none';
        el.style.zIndex = '99998';
        el.style.opacity = '0'; // Start hidden
        el.style.display = 'none'; // Start hidden
        el.innerHTML = `
          <div style="width: 100%; height: 100%;">
            ${PegadasSVG_Content}
          </div>
        `;
        el.addEventListener('animationend', () => {
          el.style.display = 'none'; // Hide when animation ends
          el.style.opacity = '0';   // Reset opacity
          particlePool.current.push(el); // Return to pool
          particleCount.current--;
        }, { once: true });
        container.appendChild(el);
        particlePool.current.push(el); // Add to pool
      }
    }

    // 3. Start event listener + render loop
    document.addEventListener('mousemove', onMouseMove, { passive: true });
    rafId.current = requestAnimationFrame(renderLoop);

    // 4. Periodic color refresh to track theme changes
    const colorInterval = setInterval(() => {
      setThemeColors(getThemeColors()); // Update state to trigger re-render if theme changes
    }, 10000);

    return () => {
      document.head.removeChild(styleEl);
      document.removeEventListener('mousemove', onMouseMove);
      cancelAnimationFrame(rafId.current);
      clearInterval(colorInterval);
    };
  }, [onMouseMove, renderLoop, themeColors]); // Add themeColors to dependency array

  return (
    <>
      {/* Main cursor element — positioned via rAF loop, never re-rendered */}
      <div
        ref={cursorRef}
        style={{
          position: 'fixed',
          left: -200,
          top: -200,
          width: CURSOR_SIZE,
          height: CURSOR_SIZE,
          pointerEvents: 'none',
          zIndex: 99999,
          willChange: 'left, top, transform',
          transition: 'transform 0.12s ease-out, filter 0.3s ease',
        }}
      />

      {/* Particle container — children managed via direct DOM APIs */}
      <div
        ref={particleContainerRef}
        style={{
          position: 'fixed',
          left: 0,
          top: 0,
          width: 0,
          height: 0,
          overflow: 'visible',
          pointerEvents: 'none',
          zIndex: 99998,
        }}
      />
    </>
  );
};

export default CustomCursor;